### ISSUE TITLE
Migrate to MAUI

### ISSUE THREAD

**Issue by IeuanWalker** [IeuanWalker/Xamarin.Forms.Breadcrumb#94]
This is on my ToDo list, but just depends when I have time.

I'm open to PRs for this to help speed things up, but please leave a comment below if you want to pick this up.

**Comment by vde-developer** [comment]
I've looked into this since I wanted an excuse to work with Maui. I was able to get it running, but there are still a lot of issues with styling and animations.

![image](https://user-images.githubusercontent.com/101636831/166099401-ecddccae-a1fc-4442-b91f-bdcd4a396d57.png)

As far as i know, pancakeview isn't supported on Maui so i just used the normal Frame.

**Comment by IeuanWalker** [comment]
@vde-developer Thats great, ye the plan is to change to use frame instead and expose the new properties available on that.

Do you mind publishing a repo or forking mine so i can see the changes?

**Comment by IeuanWalker** [comment]
Maui repo - https://github.com/IeuanWalker/Maui.Breadcrumb
